### ISSUE TITLE
Tela Em viagem

### ISSUE THREAD

**Issue by fabianogsantos** [GabrielTBeserra/AppCoopertransc#10]
@GabrielTBeserra 

- remover kilometragem
- ordenar as viagens: primeiro as aceitas e depois as recusadas
- remover: Viajou em 
- remover: Diferença de dias
- colocar: hora da marcação
- formatar cada viagem de acordo com o tipo do caminhão, como na tela da vez
- Nos dados do veículo: deixar somente o tipo e a placa

**Comment by GabrielTBeserra** [comment]
Concluido aguardando validação

**Comment by fabianogsantos** [comment]
Ok

**Comment by fabianogsantos** [comment]
Ok
